[ranges.python]
include = ["src/**/*.py", "tests/**/*.py"]
default = true

[ranges.config]
include = ["pyproject.toml"]

[ranges.python-src]
include = ["src/**/*.py"]

[ranges.python-tests]
include = ["tests/**/*.py"]

# A branch may take on debt in one metric if it pays off as much elsewhere.
[check]
policy = "sum"

# Formatting

[[metrics]]
base = "tingle.builtins.black.fmt_comment"

[[metrics]]
base = "tingle.builtins.taplo.ignore_comment"

# Linting

[[metrics]]
base = "tingle.builtins.codespell.ignore_comment"
group = "linting"

[[metrics]]
base = "tingle.builtins.ruff.noqa_comment"

[[metrics]]
name = "ruff-comment"
type = "regex_count"
group = "linting"
pattern = '#\s*ruff:'

[[metrics]]
base = "tingle.builtins.ruff.lint_ignores"

[[metrics]]
base = "tingle.builtins.ruff.per_file_ignores"

[[metrics]]
base = "tingle.builtins.pylint.disable_comment"

[[metrics]]
base = "tingle.builtins.pylint.rcfile_disables"
name = "pylint-disables"

# testing

[[metrics]]
name = "pragma-comment"
type = "regex_count"
group = "testing"
pattern = '#\s*pragma'
ranges = ["python-tests"]


[[metrics]]
name = "mock-ANY"
type = "regex_count"
group = "testing"
pattern = '^(?!.*(?:\b|_)(view|form|import)\b).*\bANY\b'
flags = ["MULTILINE"]
ranges = ["python-tests"]


[[metrics]]
name = "pytest-skip"
type = "regex_count"
group = "testing"
pattern = 'mark\.skip'
ranges = ["python-tests"]


[[metrics]]
name = "pytest-xfail"
type = "regex_count"
group = "testing"
pattern = 'mark\.xfail'
ranges = ["python-tests"]

# typing

[[metrics]]
base = "tingle.builtins.mypy.type_ignore_comment"
ranges = ["python-src"]

[[metrics]]
base = "tingle.builtins.mypy.overrides"

[[metrics]]
base = "tingle.builtins.python.any_used"
name = "type-any"
ranges = ["python-src"]

[[metrics]]
name = "type-object"
type = "symbol_uses"
group = "typing"
symbol = "object"
ranges = ["python-src"]

[[metrics]]
name = "type-cast"
type = "symbol_uses"
group = "typing"
symbol = 'cast'
ranges = ["python-src"]

[[metrics]]
name = "mypy-strictness-holes"
type = "regex_count"
group = "typing"
pattern = 'disallow_\w+ = false'
ranges = ["config"]

# Refactoring

[[metrics]]
base = "tingle.builtins.python.todo_comments"
group = "refactoring"
pattern = '#\s*(TODO|FIXME|XXX|HACK)'
ranges = ["python-src"]
