"""The ritual author's door.

Everything here is what a rituals.py — or a folio implementing a medium —
reaches for, and nothing else. The CLI lives in the root project; the cast
runtime is reached through `vekna.lexicon._inits`.
"""

from ._mills.dispatch import medium, ritual, step
from ._mills.engine import (
    CODING_FOCUS,
    SHELL_FOCUS,
    FocusSlot,
    RiteContext,
    current_rite,
    emit_delta,
    offer_prompt,
    record_result,
    replayed,
    status,
)
from ._pacts import (
    AskFn,
    Channel,
    CodingCall,
    CodingFocusProtocol,
    Directory,
    Done,
    File,
    FocusMissingError,
    FocusReply,
    GateFn,
    GitRef,
    Goto,
    MediumBoundaryError,
    NoComponents,
    RitualBoundaryError,
    RitualDefinitionError,
    RitualError,
    ShellCall,
    ShellFocusProtocol,
    ShellReply,
    StandalonePromptError,
    StepBoundaryError,
    StepBudgetExceededError,
    StringOutput,
    Text,
    TextSpec,
    Transition,
    Url,
    done,
    goto,
    sha256_of,
)

__all__ = [
    "CODING_FOCUS",
    "SHELL_FOCUS",
    "AskFn",
    "Channel",
    "CodingCall",
    "CodingFocusProtocol",
    "Directory",
    "Done",
    "File",
    "FocusMissingError",
    "FocusReply",
    "FocusSlot",
    "GateFn",
    "GitRef",
    "Goto",
    "MediumBoundaryError",
    "NoComponents",
    "RiteContext",
    "RitualBoundaryError",
    "RitualDefinitionError",
    "RitualError",
    "ShellCall",
    "ShellFocusProtocol",
    "ShellReply",
    "StandalonePromptError",
    "StepBoundaryError",
    "StepBudgetExceededError",
    "StringOutput",
    "Text",
    "TextSpec",
    "Transition",
    "Url",
    "current_rite",
    "done",
    "emit_delta",
    "goto",
    "medium",
    "offer_prompt",
    "record_result",
    "replayed",
    "ritual",
    "sha256_of",
    "status",
    "step",
]
