---
name: CI

on:
  pull_request:
    paths-ignore: ["docs/**", "mkdocs.yml"]

  push:
    branches: ["main"]
    paths-ignore: ["docs/**", "mkdocs.yml"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4
      - run: mise install
      - run: poetry install
      - run: mise run lint:py

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    env:
      MISE_PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4
      - run: mise install
      - run: poetry install
      - run: mise run test:py:cov
      - run: mise exec -- coverage xml

      # Combine and upload
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        if: ${{ !cancelled() && matrix.python-version == '3.11' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
